### PR TITLE
Solved #3 Branching

### PR DESCRIPTION
**Pull request by Akshit-Nandan**
Solved #3 
Created 3  repos.
Merged all 3 repos.
image
image
image

### CODE REVIEW

**Comment by aadi58002** [comment]
Excellent Pull request
But try to improve a title a little.

**Comment by Akshit-Nandan** [comment]
> Excellent Pull request But try to improve a title a little.

Sir can you suggest what would be the better title ?

**Comment by aadi58002** [comment]
First I would not put #3 there. As that is not a issue link which can be followed.
Some like
'Merging branch practice' or 'Practicing branches in git' or anything along a short 5-6 word description. Well this issue is not very describable but in real world there are very good example of titles

**Comment by Akshit-Nandan** [comment]
> First I would not put #3 there. As that is not a issue link which can be followed. Some like 'Merging branch practice' or 'Practicing branches in git' or anything along a short 5-6 word description. Well this issue is not very describable but in real world there are very good example of titles

thank you sir for the guidance

**Pull request closed without merging**
